imports:
    - php

filter:
    excluded_paths: [vendor/*, 
        test/*, 
        src/Controller/*, 
        src/Dice/*,
        src/Repository/*, 
        src/Card/DeckSession.php,
        src/Entity/*]

build:
    image: default-bionic

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3

        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    #- phpcs-run # Not used, missing config file
    tests:
        override:
            -   command: XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=docs/coverage.clover --coverage-filter=src

                coverage:
                    file: "docs/coverage.clover"
                    format: "php-clover"
