imports:
    - php

filter:
    excluded_paths: [vendor/*, 
        test/*, 
        src/Controller/DiceGameController.php, 
        src/Controller/LuckyControllerTwig.php, 
        src/Controller/LuckyControllerJson.php, 
        src/Controller/LuckyController.php, 
        src/Controller/LibraryController.php, 
        src/Dice/*,src/Repository/*, 
        src/Entity/*]

build:
    image: default-bionic

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3

        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    #- phpcs-run # Not used, missing config file
    tests:
        override:
            -   command: XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=docs/coverage.clover --coverage-filter=src

                coverage:
                    file: "docs/coverage.clover"
                    format: "php-clover"
